### ISSUE TITLE
[META]: Data Prepper publication and publish

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/data-prepper-documentation-website#2]
Before we can publish the new Data Prepper documentation section and make the repo public, we need to complete the following tasks. Each task is separated by the team responsible for each item.

**Repo items** (@Naarcha-AWS)

- [ ] Update maintainers.md and codeowners.md
- [ ] Make sure the `nav_order` for the documentation is properly set.
- [ ] Add necessary version labels.
- [ ] Add necessary Git workflows. (Work with @kolchfa-AWS)
- [ ] (Blocked by pipelines) Carry over all updates from documentation-website and remove the Data Prepper section from that repo.
- [ ] Make necessary updates to header in project-website and documentation-website repos.

**Backend items** (@seanneumann and @AMoo-Miki)

- [ ] Create deployment pipelines for the data-prepper repo.
- [ ] Create pipeline based on versions.json. As of May 23, we plan on only supporting Data Prepper 2.x. However, we will add 3.x later this year.

Please feel free to add any additional items we need in the comments.

**Comment by hdhalter** [comment]
@Naarcha-AWS @dlvenable - Should we close this issue? I assume we are going to keep the docs in the main doc repo since we have a working strategy.

**Comment by dblock** [comment]
[Triage -- attendees [1](https://github.com/dblock), [2](https://github.com/peternied), [3](https://github.com/reta), [4](https://github.com/krisfreedain), [5](https://github.com/Getsaurabh02), [6](https://github.com/gkamat), [7](https://github.com/scrawfor99)]
